begin;

-- ============================================================
-- 1. EJECUCIONES DEL PIPELINE DE CALIDAD
-- ============================================================

create table if not exists public.calidad_runs (
    id uuid primary key default gen_random_uuid(),

    started_at timestamptz not null default now(),
    finished_at timestamptz,

    origen text not null default 'github_actions'
        check (
            origen in (
                'github_actions',
                'apps_script',
                'manual',
                'docker'
            )
        ),

    huella text,

    filas_crudas integer not null default 0
        check (filas_crudas >= 0),

    filas_limpias integer not null default 0
        check (filas_limpias >= 0),

    facturacion_cruda numeric(18,2),
    facturacion_limpia numeric(18,2),

    incidencias jsonb not null default '[]'::jsonb,

    estado text not null default 'running'
        check (
            estado in (
                'running',
                'ok',
                'unchanged',
                'error'
            )
        ),

    mensaje text,
    version_puerta integer,

    created_at timestamptz not null default now()
);


-- ============================================================
-- 2. DATOS CRUDOS PROCEDENTES DE GOOGLE SHEETS
-- ============================================================

create table if not exists public.ventas_raw (
    id bigint generated by default as identity primary key,

    sync_id uuid not null,
    fila_origen bigint not null,

    pedido_id text,
    fecha text,
    comercial text,
    zona text,
    cliente text,
    tipo_cliente text,
    producto text,
    familia text,
    cantidad text,
    precio_unitario text,
    importe text,

    raw_payload jsonb not null default '{}'::jsonb,

    imported_at timestamptz not null default now()
);


-- ============================================================
-- 3. DATOS LIMPIOS QUE UTILIZARÁ LA APP
-- ============================================================

create table if not exists public.ventas_clean (
    pedido_id text primary key
        check (length(trim(pedido_id)) > 0),

    fecha date not null,

    comercial text not null default '(sin informar)',
    zona text,
    cliente text not null,
    tipo_cliente text not null default '(sin informar)',
    producto text not null,
    familia text not null default '(sin informar)',

    cantidad numeric(14,3) not null,
    precio_unitario numeric(14,2) not null,
    importe numeric(18,2) not null,

    fila_origen bigint not null,

    es_devolucion boolean not null default false,
    sospechoso boolean not null default false,

    sync_id uuid not null,

    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),

    constraint ventas_clean_importe_no_cero
        check (importe <> 0),

    constraint ventas_clean_devolucion_consistente
        check (es_devolucion = (cantidad < 0)),

    constraint ventas_clean_importe_consistente
        check (
            abs(importe - cantidad * precio_unitario) <= 0.02
        )
);


-- ============================================================
-- 4. ESTADO ACTUAL DE LA SINCRONIZACIÓN
-- ============================================================

create table if not exists public.sync_state (
    dataset_key text primary key default 'ventas'
        check (dataset_key = 'ventas'),

    ultima_huella text,
    ultima_ejecucion_id uuid,

    ultima_sincronizacion timestamptz,
    ultima_comprobacion timestamptz,

    ultimo_estado text not null default 'never'
        check (
            ultimo_estado in (
                'never',
                'running',
                'ok',
                'unchanged',
                'error'
            )
        ),

    ultimo_error text,
    version_puerta integer,

    filas_crudas integer,
    filas_limpias integer,

    updated_at timestamptz not null default now()
);

insert into public.sync_state (dataset_key)
values ('ventas')
on conflict (dataset_key) do nothing;


-- ============================================================
-- 5. ACTUALIZACIÓN AUTOMÁTICA DE updated_at
-- ============================================================

create or replace function public.actualizar_updated_at()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
    new.updated_at = now();
    return new;
end;
$$;

drop trigger if exists trg_ventas_clean_updated_at
on public.ventas_clean;

create trigger trg_ventas_clean_updated_at
before update on public.ventas_clean
for each row
execute function public.actualizar_updated_at();

drop trigger if exists trg_sync_state_updated_at
on public.sync_state;

create trigger trg_sync_state_updated_at
before update on public.sync_state
for each row
execute function public.actualizar_updated_at();


-- ============================================================
-- 6. ÍNDICES PARA FILTROS Y DASHBOARD
-- ============================================================

create index if not exists idx_ventas_raw_sync
    on public.ventas_raw (sync_id);

create index if not exists idx_ventas_raw_pedido
    on public.ventas_raw (pedido_id);

create index if not exists idx_ventas_raw_fila
    on public.ventas_raw (fila_origen);

create index if not exists idx_ventas_clean_fecha
    on public.ventas_clean (fecha desc);

create index if not exists idx_ventas_clean_registro
    on public.ventas_clean (fila_origen desc);

create index if not exists idx_ventas_clean_comercial
    on public.ventas_clean (comercial);

create index if not exists idx_ventas_clean_cliente
    on public.ventas_clean (cliente);

create index if not exists idx_ventas_clean_producto
    on public.ventas_clean (producto);

create index if not exists idx_ventas_clean_familia
    on public.ventas_clean (familia);

create index if not exists idx_ventas_clean_zona
    on public.ventas_clean (zona);

create index if not exists idx_ventas_clean_tipo_cliente
    on public.ventas_clean (tipo_cliente);

create index if not exists idx_ventas_clean_sospechosos
    on public.ventas_clean (sospechoso)
    where sospechoso = true;

create index if not exists idx_ventas_clean_devoluciones
    on public.ventas_clean (es_devolucion)
    where es_devolucion = true;

create index if not exists idx_calidad_runs_fecha
    on public.calidad_runs (started_at desc);


-- ============================================================
-- 7. SEGURIDAD RLS
-- ============================================================

alter table public.ventas_raw enable row level security;
alter table public.ventas_clean enable row level security;
alter table public.calidad_runs enable row level security;
alter table public.sync_state enable row level security;


-- ============================================================
-- 8. PERMISOS
-- ============================================================

revoke all on table public.ventas_raw
from anon, authenticated;

revoke all on table public.ventas_clean
from anon, authenticated;

revoke all on table public.calidad_runs
from anon, authenticated;

revoke all on table public.sync_state
from anon, authenticated;

grant select, insert, update, delete, truncate
on table public.ventas_raw
to service_role;

grant select, insert, update, delete, truncate
on table public.ventas_clean
to service_role;

grant select, insert, update, delete
on table public.calidad_runs
to service_role;

grant select, insert, update, delete
on table public.sync_state
to service_role;

grant usage, select
on sequence public.ventas_raw_id_seq
to service_role;

revoke all
on sequence public.ventas_raw_id_seq
from anon, authenticated;

revoke execute
on function public.actualizar_updated_at()
from public, anon, authenticated;

commit;
