begin;

-- Tablas temporales de carga. El pipeline escribe aqui primero.
-- Solo cuando ambas cargas terminan se publica el nuevo dataset.

create table if not exists public.ventas_raw_staging (
    id bigint generated by default as identity primary key,
    sync_id uuid not null,
    fila_origen bigint not null,
    pedido_id text,
    fecha text,
    comercial text,
    zona text,
    cliente text,
    tipo_cliente text,
    producto text,
    familia text,
    cantidad text,
    precio_unitario text,
    importe text,
    raw_payload jsonb not null default '{}'::jsonb,
    imported_at timestamptz not null default now(),
    constraint ventas_raw_staging_sync_fila_unique unique (sync_id, fila_origen)
);

create table if not exists public.ventas_clean_staging (
    sync_id uuid not null,
    pedido_id text not null,
    fecha date not null,
    comercial text not null default '(sin informar)',
    zona text,
    cliente text not null,
    tipo_cliente text not null default '(sin informar)',
    producto text not null,
    familia text not null default '(sin informar)',
    cantidad numeric(14,3) not null,
    precio_unitario numeric(14,2) not null,
    importe numeric(18,2) not null,
    fila_origen bigint not null,
    es_devolucion boolean not null default false,
    sospechoso boolean not null default false,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    primary key (sync_id, pedido_id),
    constraint ventas_clean_staging_importe_no_cero check (importe <> 0),
    constraint ventas_clean_staging_devolucion_consistente
        check (es_devolucion = (cantidad < 0)),
    constraint ventas_clean_staging_importe_consistente
        check (abs(importe - cantidad * precio_unitario) <= 0.02)
);

create index if not exists idx_ventas_raw_staging_sync
    on public.ventas_raw_staging (sync_id);

create index if not exists idx_ventas_clean_staging_sync
    on public.ventas_clean_staging (sync_id);

alter table public.ventas_raw_staging enable row level security;
alter table public.ventas_clean_staging enable row level security;

revoke all on table public.ventas_raw_staging from anon, authenticated;
revoke all on table public.ventas_clean_staging from anon, authenticated;

revoke all on sequence public.ventas_raw_staging_id_seq from anon, authenticated;

grant select, insert, update, delete, truncate
on table public.ventas_raw_staging
to service_role;

grant select, insert, update, delete, truncate
on table public.ventas_clean_staging
to service_role;

grant usage, select
on sequence public.ventas_raw_staging_id_seq
to service_role;

-- Publicacion atomica: si cualquier operacion falla, PostgreSQL revierte todo
-- y las tablas activas conservan el dataset anterior.
create or replace function public.publicar_sync(p_sync_id uuid)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
    n_raw bigint;
    n_clean bigint;
begin
    select count(*) into n_raw
    from public.ventas_raw_staging
    where sync_id = p_sync_id;

    select count(*) into n_clean
    from public.ventas_clean_staging
    where sync_id = p_sync_id;

    if n_raw = 0 then
        raise exception 'La carga raw del sync % esta vacia', p_sync_id;
    end if;

    if n_clean = 0 then
        raise exception 'La carga clean del sync % esta vacia', p_sync_id;
    end if;

    -- Supabase protege los DELETE sin filtro. Estas condiciones son siempre
    -- verdaderas para las filas válidas y mantienen la publicación transaccional.
    delete from public.ventas_raw
    where id is not null;

    insert into public.ventas_raw (
        sync_id, fila_origen, pedido_id, fecha, comercial, zona,
        cliente, tipo_cliente, producto, familia, cantidad,
        precio_unitario, importe, raw_payload, imported_at
    )
    select
        sync_id, fila_origen, pedido_id, fecha, comercial, zona,
        cliente, tipo_cliente, producto, familia, cantidad,
        precio_unitario, importe, raw_payload, imported_at
    from public.ventas_raw_staging
    where sync_id = p_sync_id
    order by fila_origen;

    delete from public.ventas_clean
    where pedido_id is not null;

    insert into public.ventas_clean (
        pedido_id, fecha, comercial, zona, cliente, tipo_cliente,
        producto, familia, cantidad, precio_unitario, importe,
        fila_origen, es_devolucion, sospechoso, sync_id,
        created_at, updated_at
    )
    select
        pedido_id, fecha, comercial, zona, cliente, tipo_cliente,
        producto, familia, cantidad, precio_unitario, importe,
        fila_origen, es_devolucion, sospechoso, sync_id,
        created_at, updated_at
    from public.ventas_clean_staging
    where sync_id = p_sync_id
    order by fecha, pedido_id;

    delete from public.ventas_raw_staging
    where sync_id = p_sync_id;

    delete from public.ventas_clean_staging
    where sync_id = p_sync_id;

    -- Limpieza de restos de cargas fallidas antiguas.
    delete from public.ventas_raw_staging
    where imported_at < now() - interval '7 days';

    delete from public.ventas_clean_staging
    where created_at < now() - interval '7 days';
end;
$$;

revoke execute on function public.publicar_sync(uuid)
from public, anon, authenticated;

grant execute on function public.publicar_sync(uuid)
to service_role;

commit;
